# Generated by Django 6.0 on 2025-12-24 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=80)),
                ('apellido_materno', models.CharField(max_length=80)),
                ('direccion', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=80)),
                ('fono', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('ciudad', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('alumno_rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='api.alumno')),
                ('curso_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='api.curso')),
                ('sucrusal_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='api.sucursal')),
            ],
        ),
    ]
