# Generated by Django 4.2 on 2025-12-26 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matricula',
            old_name='sucrusal_codigo',
            new_name='sucursal_codigo',
        ),
    ]
